export const keywordGroups = {
  opening: [
    'buenos días',
    'buenas tardes',
    'buenas noches',
    'cómo está',
    'como esta',
    'mi nombre es',
    'le llamo de',
    'gracias por tomar la llamada',
    'recibí su solicitud',
    'recibi su solicitud',
    'usted pidió información',
    'usted pidio informacion',
    'vio el anuncio',
    'vio un anuncio',
  ],
  discovery: [
    'familia',
    'hijos',
    'ingresos',
    'retiro',
    'ahorro',
    'beneficiario',
    'prioridad',
    'protección familiar',
    'proteccion familiar',
    'presupuesto',
    'meta',
    'objetivo',
    'retiro',
    'inversión',
    'inversion',
    'casa',
    'negocio',
    'qué le llamó la atención',
    'que le llamo la atencion',
    'qué fue lo que vio',
    'que fue lo que vio',
    'qué tiene actualmente',
    'que tiene actualmente',
    'por qué ahora',
    'por que ahora',
    'qué lo ha detenido',
    'que lo ha detenido',
    'plan actual',
    'seguro de vida',
    'depende de usted',
    'dependen de usted',
  ],
  product: [
    'iul',
    'indexed universal life',
    'seguro de vida indexado',
    'cash value',
    'valor en efectivo',
    'death benefit',
    'beneficio por muerte',
    'prima',
    'premium',
    'cap rate',
    'floor',
    'rider',
    'póliza',
    'poliza',
    'póliza de vida',
    'poliza de vida',
    'seguro permanente',
    'vida universal indexada',
    'acumulación',
    'acumulacion',
    'protección de vida',
    'proteccion de vida',
    's&p 500',
    'sp500',
    'índice',
    'indice',
  ],
  objections: [
    'solo quería información',
    'solo queria informacion',
    'nomás quería información',
    'nomas queria informacion',
    'nada más quería información',
    'nada mas queria informacion',
    'mándame información',
    'mandame informacion',
    'mándeme información',
    'mandeme informacion',
    'envíame información',
    'enviame informacion',
    'me manda algo',
    'me mandas algo',
    'cuánto cuesta',
    'cuanto cuesta',
    'qué cuesta',
    'que cuesta',
    'cuál es el precio',
    'cual es el precio',
    'precio',
    'no tengo dinero',
    'no tengo presupuesto',
    'está caro',
    'esta caro',
    'muy caro',
    'lo voy a pensar',
    'dejeme pensarlo',
    'déjeme pensarlo',
    'lo reviso',
    'lo reviso después',
    'lo reviso despues',
    'después vemos',
    'despues vemos',
    'no me interesa',
    'ya tengo seguro',
    'ya tengo aseguranza',
    'necesito hablar con mi esposa',
    'necesito hablar con mi esposo',
    'hablar con mi pareja',
    'lo tengo que hablar',
    'lo quiero consultar',
    'no confío',
    'no confio',
    'no entiendo',
    'no estoy seguro',
    'no estoy segura',
    'no sé',
    'no se',
    'depende',
    'no es prioridad',
    'ahorita no',
  ],
  risk: [
    'garantizado',
    'rendimiento seguro',
    'sin riesgo',
    'inversión garantizada',
    'inversion garantizada',
    'te vas a hacer rico',
    'ganancia garantizada',
    'siempre crece',
    'todos califican',
    'aprobación garantizada',
    'aprobacion garantizada',
    'cobertura garantizada',
    'no puede perder',
    'no vas a perder',
  ],
  closing: [
    'empezamos',
    'siguiente paso',
    'aplicación',
    'aplicacion',
    'firma',
    'cuenta bancaria',
    'fecha de nacimiento',
    'vamos a completar',
    'si califico',
    'si calificas',
    'si lo aprueban',
    'si te aprueban',
    'revisar si califica',
    'revisar si calificas',
    'qué le ves de malo',
    'que le ves de malo',
    'qué negativo',
    'que negativo',
    'avanzar',
    'aplicar',
    'aprobación',
    'aprobacion',
  ],
  followUp: [
    'lo llamo después',
    'lo llamo despues',
    'qué día le queda bien',
    'que dia le queda bien',
    'agendamos',
    'le mando información',
    'le mando informacion',
    'seguimos mañana',
    'mañana',
    'manana',
    'la próxima semana',
    'la proxima semana',
    'otro día',
    'otro dia',
    'mejor luego',
    'lo vemos luego',
  ],
} as const;

export function findMatches(text: string, keywords: readonly string[]): string[] {
  const normalized = text.toLocaleLowerCase('es');
  return keywords.filter((kw) => normalized.includes(kw.toLocaleLowerCase('es')));
}
