export const keywordGroups = {
  opening: [
    'buenos días',
    'buenas tardes',
    'buenas noches',
    'cómo está',
    'como esta',
    'mi nombre es',
    'le llamo de',
    'gracias por tomar la llamada',
  ],
  discovery: [
    'familia',
    'hijos',
    'ingresos',
    'retiro',
    'ahorro',
    'beneficiario',
    'prioridad',
    'protección familiar',
    'proteccion familiar',
    'presupuesto',
  ],
  product: [
    'iul',
    'indexed universal life',
    'seguro de vida indexado',
    'cash value',
    'valor en efectivo',
    'death benefit',
    'beneficio por muerte',
    'prima',
    'premium',
    'cap rate',
    'floor',
    'rider',
    'póliza',
    'poliza',
  ],
  objections: [
    'no tengo dinero',
    'no tengo presupuesto',
    'está caro',
    'esta caro',
    'muy caro',
    'lo voy a pensar',
    'dejeme pensarlo',
    'déjeme pensarlo',
    'mándeme información',
    'mandeme informacion',
    'no me interesa',
    'ya tengo seguro',
    'necesito hablar con mi esposa',
    'necesito hablar con mi esposo',
    'no confío',
    'no confio',
    'no entiendo',
  ],
  risk: [
    'garantizado',
    'rendimiento seguro',
    'sin riesgo',
    'inversión garantizada',
    'inversion garantizada',
    'te vas a hacer rico',
  ],
  closing: [
    'empezamos',
    'siguiente paso',
    'aplicación',
    'aplicacion',
    'firma',
    'cuenta bancaria',
    'fecha de nacimiento',
    'vamos a completar',
  ],
  followUp: [
    'lo llamo después',
    'lo llamo despues',
    'qué día le queda bien',
    'que dia le queda bien',
    'agendamos',
    'le mando información',
    'le mando informacion',
    'seguimos mañana',
  ],
} as const;

export function findMatches(text: string, keywords: readonly string[]): string[] {
  const normalized = text.toLocaleLowerCase('es');
  return keywords.filter((kw) => normalized.includes(kw.toLocaleLowerCase('es')));
}
